# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Democracia Global
email: info@democracia.global
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

## prose.io config
prose:
  rooturl: '_posts'
  ignore: ['file_a.html', '_config.yml']
  siteurl: 'http://beta.democracia.global/'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img'
    metadata:
    _posts/union:
      - name: "category"
        field:
          element: "hidden"
          value: "Union"
    _posts/country:
      - name: "category"
        field:
          element: "hidden"
          value: "Country"
    _posts/region_1:
      - name: "category"
        field:
          element: "hidden"
          value: "Autonomous Area"
    _posts/region_4:
      - name: "category"
        field:
          element: "hidden"
          value: "Municipality"
    _posts/party:
      - name: "category"
        field:
          element: "hidden"
          value: "Political Party"
    _posts/result:
      - name: "category"
        field:
          element: "hidden"
          value: "Election Result"